Repository wecode-bootcamp-korea/31-2nd-bbooing-frontend, pull requests merged in 2022-04, with the labels that each got.

#2 [31기 김정수] ADD:공통컴포넌트 footer 레이아웃추가
  public/images/free-icon-network-7185719.png
  public/images/free-icon-youtube-1384012.png
  public/images/premium-icon-facebook-665209.png
  public/images/premium-icon-instagram-665211.png
  src/components/Footer/Footer.js
  src/components/Footer/FooterTop.js
Labels: Status: 리뷰 요청

#1 [31]기 김정수 ADD:nav 기본 레이아웃
  .gitignore
  public/images/ae48164a98e4aa612a6cfeb8a59261e5f64f7966.jpg
  public/images/logo.svg
  src/assets/img.png
  src/assets/premium-icon-magnifier-2311526.png
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#4 [31기 김정수] ADD:로그인 페이지 레이아웃 / 소셜 로그인 구현
  public/images/kakao_login_medium_wide.png
  public/images/login background img.jpg
  public/index.html
  src/config.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#8 [31기 김정수] ADD,MOIDFY: NAV Z-index값 및 스타일 수정 localstorage부분 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#9 [31기 김정수] 로그인페이지 ADD/MODIFY: utils 추가 / 코드 수정
  src/pages/Login/Login.js
  src/utils.js
Labels: Status: 리뷰 요청

#10 [31기 김정수] modify: main페이지 login 부분 조건부렌더링
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#12 [31기 김정수] 공통컴포넌트 footer 이미지 경로 수정
  src/components/Footer/Footer.js
Labels: Status: Accepted

#14 [31기 김정수] login /add/ modify: utils.js 로컬스토리지 비우는 함수 작성 로그아웃 임시생성
  src/pages/Login/Login.js
  src/utils.js
Labels: Status: 리뷰 요청

#15 [31기 김정수] 공통컴포넌트 NAV : add/modify 프론트적인 로그아웃 구현 , 이미지 스타일 값 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#17 [31기 김정수] modify : nav 로그아웃 방식 변경
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#18 [31기 김효정] 메인 브랜치 버그, conflict 해결 및 찜 기능 통신 기능 추가
  src/components/Card/Card.js
  src/components/Nav/Nav.js
  src/config.js
  src/hooks/useWishList.js
  src/hooks/useWishListCheck.js
  src/index.js
  src/pages/LectureList/LectureList.js
  src/pages/Main/Components/LectureSlide.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#20 [31기 김정수] 카카오 로그인 fix: kakao inialize already 에러 해결 / init 중복 없애고 index에서 한번 실행
  src/components/Nav/Nav.js
  src/index.js
  src/pages/Login/Login.js
  yarn.lock
Labels: Status: 리뷰 요청

#11 [31기 임재혁]Modify:리뷰반영 /Wish list UI 및 통신 완료
  public/data/WishList.json
  src/components/Review/Comment.js
  src/config.js
  src/pages/WishList/WishComponent/WishContents.js
  src/pages/WishList/WishList.js
Labels: Status: 리뷰 요청

#5 [31기 구본희] Add : 상세페이지 구조작업
  package-lock.json
  package.json
  public/data/courseData.json
  src/components/Card/Card.js
  src/config.js
  src/pages/LectureDetail/Header.js
  src/pages/LectureDetail/ImageViewer.js
  src/pages/LectureDetail/InfoSection.js
  src/pages/LectureDetail/LectureDetail.js
  src/pages/LectureDetail/ScrollNav.js
  src/pages/LectureDetail/StickyNav.js
  yarn.lock
Labels: Status: 수정 요청

#7 [31기 임재혁]ADD: 리뷰페이지 레이아웃 추가
  package-lock.json
  package.json
  public/data/commentData.json
  src/Router.js
  src/components/Review/Comment.js
  src/components/Review/Review.js
Labels: Status: 수정 요청
